# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: CoreBao
email: mxi.huang@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  专注Web开发技术PHP,MySQL,Linux
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://blog.corebao.com" # the base hostname & protocol for your site
twitter_username: max4gh
github_username:  max4gh
desc: 用技术促进生产力发展！

# Build settings
markdown: kramdown
